secrets:
    ga_passphrase:
        external: true
    ga_gdrive_client_secret:
        external: true

volumes:
    ga_credentials:
        external: true
    ga_cache:
        external: true

services:
    ga:
        build:
            context: "."
        network_mode: host
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - type: bind
              source: "./exampledata"
              target: "/mnt"
            - type: volume
              source: ga_credentials
              target: "/var/lib/duplicity"
            - type: volume
              source: ga_cache
              target: "/usr/lib/duplicity/.cache/duplicity"        
        environment:
            MODE: "backup"
            DUPLICITY_TARGET_URL: "gdrive://641079776729-da3fi7a2kgk5jkutsjdcnhugqolu40mo.apps.googleusercontent.com/this?myDriveFolderID=1_8rQ4E8ssoN-guFrGs7CC2IFofXBaimi"
            GOOGLE_CLIENT_SECRET_JSON_FILE: "/run/secrets/google_client_secret"
            DUPLICITY_PASSPHRASE_FILE: "/run/secrets/duplicity_passphrase"
            GOOGLE_CREDENTIALS_FILE: "/var/lib/duplicity/google_credentials"
            GOOGLE_OAUTH_LOCAL_SERVER_HOST: "localhost"
            GOOGLE_OAUTH_LOCAL_SERVER_PORT: "80"
        secrets:
            - ga_passphrase
            - ga_gdrive_client_secret
